language: r
cache: packages
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: false
r_github_packages:
- rstudio/bookdown
- mjskay/tidybayes
r_packages:
- tidyverse
- forcats
- broom
- Cairo
- effsize
- coin
- rstan
- devtools
- MASS
- ggstance
- afex
- import
- brms